DSCHUFS/Solution_Challenge_WSC

public/index.html
=> Update html file

newsletter/email.js, newsletter/testmail.html
뉴스레터 기능 구현.
nodeMailer 사용
FireBase 연결 성공 -> FireBase에 저장된 item들을 반복문을 돌면서 가져오고, 각 각 메일주소로 메일을 보낸다!
=> Add newsletter function

public/script/pageTransition.js, public/style.css, views/index.ejs
제출하기 누르고 나면, 새로고침을 하지 않는 한 test div는 보이지 않음. 결과 div만 계속 떠있다.
=> Add test Result DIV

server.js, views/index.ejs
- 기존 소켓 통신으로만 feedback chart를 생성하여, 새로고침 시 차트가 보이지 않았음
- index.ejs 라우팅 시, 넘겨준 db data를 저장하여 chart 생성함으로 해결
=> Add feedback chart source when reload

public/script/pageTransition.js, public/style.css
=> Fix the transition error

public/script/pageTransition.js, public/style.css, views/index.ejs
=> Change Youtbe carousel

public/style.css, views/index.ejs
- Layout of the main bottom
- hide and show (the comment of image carousel)
=> Modify the main bottom and the comment of image carousel

server.js, views/index.ejs
- 기존은 유저가 테스트 제출한 후, socket 통신을 통해, 테스트 시점에 따라 다른 소켓 메시지를 보내어 상황에 맞는 alert를 실행하던 방식
- 제출버튼 눌렀을 때, ajax 통신이 성공하면 적절한 alert 실행하는 방식으로 변경
=> Modify alert system after submit test

public/style.css, views/atResult.ejs, views/index.ejs
=> Add footer

public/script/useCookies.js, public/style.css, views/index.ejs
-  쿠키 test: done을 파악해서 테스트 안본사람에게는 점수 대신 돌아가서 테스트를 보라는 텍스트를 띄워줌.
=> Modify before test done

package-lock.json, package.json, public/style.css, server.js, views/atResult.ejs, views/btResult.ejs, views/index.ejs
- 사용자별로 닉네임을 입력 받아, 사용자별로 인식(세션에 닉네임 저장)
=> Modify a way of user recognition from cookie to session

public/script/pageTransition.js, public/script/useCookies.js, views/atResult.ejs, views/btResult.ejs, views/index.ejs
=> Modify submit button

public/script/pageTransition.js, public/style.css, views/index.ejs
- Layout of nickname input window
- Prevent event when there are no any input
=> Modify nickname input window

public/style.css
- Modify nickname input error 
- Modify .form-control, button {z-index:0 --> 10}
=> Modify nickname input error

public/script/pageTransition.js
- Addeventlistner to first test button
=> Modify the first test button error

views/afterTest.ejs
=> Update test UI

views/index.ejs
메인에 있는 테스트하러가기 버튼 수정
-이미 등록된 사람일 경우 & 닉네임 정상등록인 경우 만 test 페이지로 넘어가게 설정
=> Edit mainTotest Button

package-lock.json, server.js, views/index.ejs
문제 변경 및 추가에 따른 서버 및 클라이언트 문서 수정
=> Modify scoring source

views/afterTest.ejs, views/beforeTest.ejs
=> Modify the test input value

public/style.css, views/index.ejs
=> Modify nickename container

public/style.css
=> Modify image carousel height

public/style.css, views/index.ejs
=> Add the comment above image carousel

public/style.css, views/afterTest.ejs, views/atResult.ejs, views/beforeTest.ejs, views/btResult.ejs, views/index.ejs
test 페이지 전반적인 수정
모바일에서 봤을 때, 글씨 이상하지 않도록 css 조정
kakao 아이콘 옆에 공유해달라고 문구 추가
=> Edit test pages

views/index.ejs
=> Add translate button mouseover

public/script/chartArguments.js, public/script/pageTransition.js, public/script/translation.js, public/style.css, server.js, views/en_afterTest.ejs, views/en_atResult.ejs, views/en_beforeTest.ejs, views/en_btResult.ejs, views/en_index.ejs
=> Add the page translated into English

views/en_index.ejs, views/index.ejs
=> Modify the menu button

README.md, public/style.css, views/en_index.ejs, views/index.ejs
유튜브 영상추가
aftertest result에서 버튼 두개 색깔 바꿈
=> Add youtube video
